before_install:
- openssl aes-256-cbc -K $encrypted_5ce6662f555d_key -iv $encrypted_5ce6662f555d_iv
  -in resume-vcm.json.enc -out resume-vcm.json -d
language: node_js
skip_files:
- "^.*node_modules(/.*)?"
node_js:
- node
script:
- npm run build
deploy:
  provider: gae,
  keyfile: resume-vcm.json
  project: resume-vcm
  skip_cleanup: true
  on: master
